<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Dorado.Domain\Dorado.Domain.csproj" />
    <ProjectReference Include="..\Dorado.Application\Dorado.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LibVLCSharp" Version="3.9.5" />
    <PackageReference Include="LibVLCSharp.Avalonia" Version="3.9.5" />
    <PackageReference Include="VideoLAN.LibVLC.Windows" Version="3.0.23.1" />
    <PackageReference Include="TagLibSharp" Version="2.3.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
