<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Headless.XUnit" Version="11.2.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.6.0" />
    <PackageReference Include="xunit" Version="2.4.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.5">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector" Version="6.0.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Dorado.Domain\Dorado.Domain.csproj" />
    <ProjectReference Include="..\..\src\Dorado.Application\Dorado.Application.csproj" />
    <ProjectReference Include="..\..\src\Dorado.Infrastructure.External\Dorado.Infrastructure.External.csproj" />
    <ProjectReference Include="..\..\src\Dorado.Infrastructure.Persistence\Dorado.Infrastructure.Persistence.csproj" />
    <ProjectReference Include="..\..\src\Dorado.Infrastructure.Audio\Dorado.Infrastructure.Audio.csproj" />
    <ProjectReference Include="..\..\src\Dorado.Plugins.Host\Dorado.Plugins.Host.csproj" />
    <ProjectReference Include="..\..\src\Dorado.Plugins.LastFm\Dorado.Plugins.LastFm.csproj" />
    <ProjectReference Include="..\..\src\Dorado.Plugins.Discord\Dorado.Plugins.Discord.csproj" />
    <ProjectReference Include="..\..\src\Dorado.UI\Dorado.UI.csproj" />
  </ItemGroup>

</Project>
