<Project>
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>12</LangVersion>
    <Authors>Heretek AI / Dorado Contributors</Authors>
    <Company>Dorado</Company>
    <Product>Dorado Media Player</Product>
    <Copyright>Copyright © 2026</Copyright>
    <RepositoryUrl>https://github.com/project-dorado/dorado</RepositoryUrl>
  </PropertyGroup>

  <PropertyGroup>
    <AvaloniaVersion>11.2.0</AvaloniaVersion>
    <CommunityToolkitMvvmVersion>8.3.2</CommunityToolkitMvvmVersion>
    <MicrosoftEfCoreVersion>8.0.10</MicrosoftEfCoreVersion>
  </PropertyGroup>
</Project>
