<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Dorado.Domain\Dorado.Domain.csproj" />
    <ProjectReference Include="..\Dorado.Application\Dorado.Application.csproj" />
    <ProjectReference Include="..\Dorado.Plugins.Protocol\Dorado.Plugins.Protocol.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
